name: ItemizerX
version: ${version}
api-version: 1.21
description: ${description}
author: unsuperiordev (Focusvity)
main: me.focusvity.itemizerx.ItemizerX
softdepend:
  - CoreProtect
commands:
  itemizer:
    description: The main command for ItemizerX
    usage: /<command>
    aliases: [ii, it]
